#swagger config
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: INFO
#    org.springframework.security: TRACE

remote-token:
  client-id: service
  client-credential: microservice
  check-authorization-url: http://localhost:9000/oauth/check_token
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-learning?useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false

